apiVersion: v1
kind: Service
metadata:
  labels:
    app: trivy-scanner
  name: trivy-scanner
spec:
  selector:
    app: trivy-scanner
  ports:
    - name: metrics
      protocol: TCP
      port: 9115
      targetPort: 9115
